# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainForm_modify.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QGroupBox,
    QHBoxLayout, QLabel, QLayout, QLineEdit,
    QPlainTextEdit, QPushButton, QRadioButton, QSizePolicy,
    QWidget)
import UI.reference.icons_rc

class Ui_mainForm(object):
    def setupUi(self, mainForm):
        if not mainForm.objectName():
            mainForm.setObjectName(u"mainForm")
        mainForm.resize(1920, 1080)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainForm.sizePolicy().hasHeightForWidth())
        mainForm.setSizePolicy(sizePolicy)
        mainForm.setMinimumSize(QSize(1920, 1080))
        mainForm.setMaximumSize(QSize(1920, 1080))
        font = QFont()
        font.setFamilies([u"Arial"])
        mainForm.setFont(font)
        mainForm.setStyleSheet(u"")
        self.widgetTopBtnBar = QWidget(mainForm)
        self.widgetTopBtnBar.setObjectName(u"widgetTopBtnBar")
        self.widgetTopBtnBar.setGeometry(QRect(0, 0, 1920, 72))
        self.widgetTopBtnBar.setMinimumSize(QSize(1920, 72))
        self.widgetTopBtnBar.setStyleSheet(u"border : 1px solid black;")
        self.widgetBtnGoHome = QWidget(self.widgetTopBtnBar)
        self.widgetBtnGoHome.setObjectName(u"widgetBtnGoHome")
        self.widgetBtnGoHome.setGeometry(QRect(0, 0, 72, 72))
        sizePolicy.setHeightForWidth(self.widgetBtnGoHome.sizePolicy().hasHeightForWidth())
        self.widgetBtnGoHome.setSizePolicy(sizePolicy)
        self.widgetBtnGoHome.setMinimumSize(QSize(72, 72))
        self.widgetBtnGoHome.setStyleSheet(u"border-radius:8px;\n"
"margin:4px;")
        self.btnGoHome = QPushButton(self.widgetBtnGoHome)
        self.btnGoHome.setObjectName(u"btnGoHome")
        self.btnGoHome.setGeometry(QRect(0, 0, 72, 72))
        self.btnGoHome.setMinimumSize(QSize(72, 72))
        self.btnGoHome.setStyleSheet(u"border: none;\n"
"background-color: transparent;\n"
"")
        self.label_home = QLabel(self.widgetBtnGoHome)
        self.label_home.setObjectName(u"label_home")
        self.label_home.setGeometry(QRect(0, 0, 72, 72))
        self.label_home.setMinimumSize(QSize(72, 72))
        self.label_home.setStyleSheet(u"border: none;\n"
"")
        self.label_home.setPixmap(QPixmap(u":/\ud648.png"))
        self.label_home.setScaledContents(True)
        self.label_home.setMargin(8)
        self.label_home.raise_()
        self.btnGoHome.raise_()
        self.widgetTimeInfo = QWidget(self.widgetTopBtnBar)
        self.widgetTimeInfo.setObjectName(u"widgetTimeInfo")
        self.widgetTimeInfo.setGeometry(QRect(980, 0, 300, 72))
        self.widgetTimeInfo.setStyleSheet(u"border: none;\n"
"")
        self.label_8 = QLabel(self.widgetTimeInfo)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 58, 16))
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QFrame.Shape.NoFrame)
        self.label_9 = QLabel(self.widgetTimeInfo)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 50, 58, 16))
        self.label_9.setFont(font)
        self.currentTime = QLabel(self.widgetTimeInfo)
        self.currentTime.setObjectName(u"currentTime")
        self.currentTime.setGeometry(QRect(90, 10, 151, 16))
        self.operationTime = QLabel(self.widgetTimeInfo)
        self.operationTime.setObjectName(u"operationTime")
        self.operationTime.setGeometry(QRect(90, 50, 101, 16))
        self.operationTime.setStyleSheet(u"")
        self.label_10 = QLabel(self.widgetTopBtnBar)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(1330, 0, 72, 72))
        self.label_10.setStyleSheet(u"border-radius : 16px;\n"
"margin : 16px\n"
"")
        self.label_10.setPixmap(QPixmap(u":/\ud50c\ub7ab\ud3fc\ub85c\ubd07.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setMargin(0)
        self.txUnitNuberInfo = QLabel(self.widgetTopBtnBar)
        self.txUnitNuberInfo.setObjectName(u"txUnitNuberInfo")
        self.txUnitNuberInfo.setGeometry(QRect(1410, 0, 120, 72))
        font1 = QFont()
        font1.setFamilies([u"D2Coding"])
        font1.setPointSize(18)
        self.txUnitNuberInfo.setFont(font1)
        self.txUnitNuberInfo.setStyleSheet(u"border : none;")
        self.txUnitNuberInfo.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.widgetbtnSetup = QWidget(self.widgetTopBtnBar)
        self.widgetbtnSetup.setObjectName(u"widgetbtnSetup")
        self.widgetbtnSetup.setGeometry(QRect(1840, 0, 72, 72))
        self.widgetbtnSetup.setStyleSheet(u"border-radius : 8px;\n"
"margin : 4px;")
        self.label_11 = QLabel(self.widgetbtnSetup)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 0, 72, 72))
        self.label_11.setStyleSheet(u"border : none;\n"
"padding : 4px;")
        self.label_11.setPixmap(QPixmap(u":/\uc124\uc815.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setMargin(8)
        self.btnGotoSetup = QPushButton(self.widgetbtnSetup)
        self.btnGotoSetup.setObjectName(u"btnGotoSetup")
        self.btnGotoSetup.setGeometry(QRect(0, 0, 72, 72))
        self.btnWaringJoin = QPushButton(self.widgetTopBtnBar)
        self.btnWaringJoin.setObjectName(u"btnWaringJoin")
        self.btnWaringJoin.setGeometry(QRect(1730, 5, 91, 21))
        self.btnWaringSend = QPushButton(self.widgetTopBtnBar)
        self.btnWaringSend.setObjectName(u"btnWaringSend")
        self.btnWaringSend.setGeometry(QRect(1720, 35, 111, 31))
        self.mainCamScreen = QWidget(mainForm)
        self.mainCamScreen.setObjectName(u"mainCamScreen")
        self.mainCamScreen.setGeometry(QRect(590, 80, 1331, 591))
        self.mainCamScreen.setStyleSheet(u"border : 1px solid black;\n"
"margin : 4px;")
        self.mainCamScreen_bmpLabel = QLabel(self.mainCamScreen)
        self.mainCamScreen_bmpLabel.setObjectName(u"mainCamScreen_bmpLabel")
        self.mainCamScreen_bmpLabel.setGeometry(QRect(0, 0, 1331, 591))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.mainCamScreen_bmpLabel.sizePolicy().hasHeightForWidth())
        self.mainCamScreen_bmpLabel.setSizePolicy(sizePolicy1)
        self.mainCamScreen_bmpLabel.setPixmap(QPixmap(u":/\uac15\uc218\ub7c9.png"))
        self.mainCamScreen_bmpLabel.setScaledContents(True)
        self.widget_zoom_in = QWidget(self.mainCamScreen)
        self.widget_zoom_in.setObjectName(u"widget_zoom_in")
        self.widget_zoom_in.setGeometry(QRect(1220, 490, 91, 81))
        self.widget_zoom_in.setStyleSheet(u"border : none;")
        self.btnZoomIn = QPushButton(self.widget_zoom_in)
        self.btnZoomIn.setObjectName(u"btnZoomIn")
        self.btnZoomIn.setGeometry(QRect(0, 0, 91, 81))
        self.label_3 = QLabel(self.widget_zoom_in)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 91, 81))
        self.label_3.setPixmap(QPixmap(u":/\ud655\ub300.png"))
        self.label_3.setScaledContents(True)
        self.label_3.raise_()
        self.btnZoomIn.raise_()
        self.widgetBottomLeftScreen = QWidget(mainForm)
        self.widgetBottomLeftScreen.setObjectName(u"widgetBottomLeftScreen")
        self.widgetBottomLeftScreen.setGeometry(QRect(0, 840, 581, 241))
        self.widgetBottomLeftScreen.setStyleSheet(u"border : 1px solid black;\n"
"margin : 4px;")
        self.widgetBottomRightScreen = QWidget(mainForm)
        self.widgetBottomRightScreen.setObjectName(u"widgetBottomRightScreen")
        self.widgetBottomRightScreen.setGeometry(QRect(0, 570, 581, 251))
        self.widgetBottomRightScreen.setStyleSheet(u"border : 1px solid black;\n"
"margin : 4px;")
        self.widgetBottomRightCam = QWidget(self.widgetBottomRightScreen)
        self.widgetBottomRightCam.setObjectName(u"widgetBottomRightCam")
        self.widgetBottomRightCam.setGeometry(QRect(450, 200, 96, 96))
        self.widgetBottomRightCam.setStyleSheet(u"border:none;")
        self.systemLog = QWidget(mainForm)
        self.systemLog.setObjectName(u"systemLog")
        self.systemLog.setGeometry(QRect(1330, 670, 591, 411))
        self.systemLog.setStyleSheet(u"border : 1px solid black;\n"
"margin : 4px;\n"
"")
        self.edLogText = QPlainTextEdit(self.systemLog)
        self.edLogText.setObjectName(u"edLogText")
        self.edLogText.setGeometry(QRect(10, 40, 571, 321))
        self.edLogText.setStyleSheet(u"background-color: rgb(0,0,0);\n"
"color : rgb(0,255,0);")
        self.edLogText.setReadOnly(True)
        self.lineEdit_cmd = QLineEdit(self.systemLog)
        self.lineEdit_cmd.setObjectName(u"lineEdit_cmd")
        self.lineEdit_cmd.setGeometry(QRect(10, 360, 341, 41))
        self.pushButton_cmd_Send = QPushButton(self.systemLog)
        self.pushButton_cmd_Send.setObjectName(u"pushButton_cmd_Send")
        self.pushButton_cmd_Send.setGeometry(QRect(350, 360, 111, 41))
        self.lbl_systemlog = QLabel(self.systemLog)
        self.lbl_systemlog.setObjectName(u"lbl_systemlog")
        self.lbl_systemlog.setGeometry(QRect(10, 10, 121, 31))
        
        self.widget_controlKeys = QWidget(mainForm)
        self.widget_controlKeys.setObjectName(u"widget_controlKeys")
        self.widget_controlKeys.setGeometry(QRect(930, 720, 401, 355))
        self.widget_controlKeys.setStyleSheet(u"border : 1px solid black;\n"
"")
        
        self.widget = QWidget(self.widget_controlKeys)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 10, 330, 330))
        self.widget.setStyleSheet(u"border:none;")
        self.widget_keydown = QWidget(self.widget)
        self.widget_keydown.setObjectName(u"widget_keydown")
        self.widget_keydown.setGeometry(QRect(90, 200, 151, 131))
        self.widget_keydown.setStyleSheet(u"border : none;")
        self.label_keydown_normal = QLabel(self.widget_keydown)
        self.label_keydown_normal.setObjectName(u"label_keydown_normal")
        self.label_keydown_normal.setGeometry(QRect(0, 0, 151, 131))
        self.label_keydown_normal.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\ud558_\uae30\ubcf8.png"))
        self.label_keydown_push = QLabel(self.widget_keydown)
        self.label_keydown_push.setObjectName(u"label_keydown_push")
        self.label_keydown_push.setEnabled(True)
        self.label_keydown_push.setGeometry(QRect(0, 0, 151, 131))
        self.label_keydown_push.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\ud558_\ub204\ub984.png"))
        self.btnKeyDown = QPushButton(self.widget_keydown)
        self.btnKeyDown.setObjectName(u"btnKeyDown")
        self.btnKeyDown.setGeometry(QRect(0, 0, 151, 131))
        self.widget_keyleft = QWidget(self.widget)
        self.widget_keyleft.setObjectName(u"widget_keyleft")
        self.widget_keyleft.setGeometry(QRect(0, 85, 120, 160))
        self.widget_keyleft.setStyleSheet(u"border : none;")
        self.label_keyleft_normal = QLabel(self.widget_keyleft)
        self.label_keyleft_normal.setObjectName(u"label_keyleft_normal")
        self.label_keyleft_normal.setGeometry(QRect(0, 0, 120, 160))
        self.label_keyleft_normal.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc88c_\uae30\ubcf8.png"))
        self.label_keyleft_push = QLabel(self.widget_keyleft)
        self.label_keyleft_push.setObjectName(u"label_keyleft_push")
        self.label_keyleft_push.setEnabled(True)
        self.label_keyleft_push.setGeometry(QRect(0, 0, 120, 160))
        self.label_keyleft_push.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc88c_\ub204\ub984.png"))
        self.btnKeyLeft = QPushButton(self.widget_keyleft)
        self.btnKeyLeft.setObjectName(u"btnKeyLeft")
        self.btnKeyLeft.setGeometry(QRect(0, 0, 120, 160))
        self.widget_keyup = QWidget(self.widget)
        self.widget_keyup.setObjectName(u"widget_keyup")
        self.widget_keyup.setGeometry(QRect(90, 0, 151, 131))
        self.widget_keyup.setStyleSheet(u"border : none;")
        self.label_keyup_normal = QLabel(self.widget_keyup)
        self.label_keyup_normal.setObjectName(u"label_keyup_normal")
        self.label_keyup_normal.setGeometry(QRect(0, 0, 151, 131))
        self.label_keyup_normal.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc0c1_\uae30\ubcf8.png"))
        self.label_keyup_push = QLabel(self.widget_keyup)
        self.label_keyup_push.setObjectName(u"label_keyup_push")
        self.label_keyup_push.setEnabled(True)
        self.label_keyup_push.setGeometry(QRect(0, 0, 151, 131))
        self.label_keyup_push.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc0c1_\ub204\ub984.png"))
        self.btnKeyUp = QPushButton(self.widget_keyup)
        self.btnKeyUp.setObjectName(u"btnKeyUp")
        self.btnKeyUp.setGeometry(QRect(0, 0, 151, 131))
        self.widget_keyright = QWidget(self.widget)
        self.widget_keyright.setObjectName(u"widget_keyright")
        self.widget_keyright.setGeometry(QRect(210, 85, 121, 161))
        self.widget_keyright.setStyleSheet(u"border : none;")
        self.label_keyright_normal = QLabel(self.widget_keyright)
        self.label_keyright_normal.setObjectName(u"label_keyright_normal")
        self.label_keyright_normal.setGeometry(QRect(0, 0, 151, 161))
        self.label_keyright_normal.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc6b0_\uae30\ubcf8.png"))
        self.label_keyright_push = QLabel(self.widget_keyright)
        self.label_keyright_push.setObjectName(u"label_keyright_push")
        self.label_keyright_push.setEnabled(True)
        self.label_keyright_push.setGeometry(QRect(0, 0, 151, 161))
        self.label_keyright_push.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc6b0_\ub204\ub984.png"))
        self.btnKeyRight = QPushButton(self.widget_keyright)
        self.btnKeyRight.setObjectName(u"btnKeyRight")
        self.btnKeyRight.setGeometry(QRect(0, 0, 151, 161))
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 150, 32, 32))
        self.label_4.setStyleSheet(u"background-color:black;\n"
"border-radius : 16px;")
        self.label_12 = QLabel(mainForm)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(930, 675, 401, 40))
        self.label_12.setStyleSheet(u"background-color:rgb(207, 207, 207);\n"
"\n"
"")
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_12.setMargin(4)        
        
        self.frameRobotControlStatus = QFrame(mainForm)
        self.frameRobotControlStatus.setObjectName(u"frameRobotControlStatus")
        self.frameRobotControlStatus.setGeometry(QRect(0, 80, 581, 271))
        self.frameRobotControlStatus.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameRobotControlStatus.setFrameShadow(QFrame.Shadow.Raised)
        self.label = QLabel(self.frameRobotControlStatus)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 581, 41))
        self.label.setStyleSheet(u"background-color:rgb(207, 207, 207);\n"
"\n"
"")
        self.label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label.setMargin(4)
        self.widget_op_mode_status = QWidget(self.frameRobotControlStatus)
        self.widget_op_mode_status.setObjectName(u"widget_op_mode_status")
        self.widget_op_mode_status.setGeometry(QRect(10, 50, 441, 91))
        self.widget_op_mode_status.setStyleSheet(u"border : 1px solid black;")
        self.label_5 = QLabel(self.widget_op_mode_status)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 0, 441, 31))
        self.label_5.setStyleSheet(u"background-color:rgb(200,200,200)")
        self.groupBox = QGroupBox(self.widget_op_mode_status)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 30, 441, 51))
        self.groupBox.setStyleSheet(u"border:none;")
        self.horizontalLayoutWidget = QWidget(self.groupBox)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 10, 401, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.rb_opmode_auto = QRadioButton(self.horizontalLayoutWidget)
        self.rb_opmode_auto.setObjectName(u"rb_opmode_auto")
        self.rb_opmode_auto.setStyleSheet(u"border:none;\n"
"")

        self.horizontalLayout.addWidget(self.rb_opmode_auto)

        self.rb_opmode_operator = QRadioButton(self.horizontalLayoutWidget)
        self.rb_opmode_operator.setObjectName(u"rb_opmode_operator")

        self.horizontalLayout.addWidget(self.rb_opmode_operator)

        self.rb_opmode_manual = QRadioButton(self.horizontalLayoutWidget)
        self.rb_opmode_manual.setObjectName(u"rb_opmode_manual")

        self.horizontalLayout.addWidget(self.rb_opmode_manual)

        self.widget_mssion_status = QWidget(self.frameRobotControlStatus)
        self.widget_mssion_status.setObjectName(u"widget_mssion_status")
        self.widget_mssion_status.setGeometry(QRect(10, 150, 441, 101))
        self.widget_mssion_status.setStyleSheet(u"border : 1px solid black;")
        self.label_6 = QLabel(self.widget_mssion_status)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 0, 441, 31))
        self.label_6.setStyleSheet(u"background-color:rgb(200,200,200)")
        self.groupBox_2 = QGroupBox(self.widget_mssion_status)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 30, 441, 71))
        self.groupBox_2.setStyleSheet(u"border:none;")
        self.horizontalLayoutWidget = QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 20, 401, 41))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.rb_ms_move = QRadioButton(self.horizontalLayoutWidget)
        self.rb_ms_move.setObjectName(u"rb_ms_move")
        self.rb_ms_move.setStyleSheet(u"border:none;\n"
"")

        self.horizontalLayout_2.addWidget(self.rb_ms_move)

        self.rb_ms_patrol = QRadioButton(self.horizontalLayoutWidget)
        self.rb_ms_patrol.setObjectName(u"rb_ms_patrol")

        self.horizontalLayout_2.addWidget(self.rb_ms_patrol)

        self.rb_ms_tracking = QRadioButton(self.horizontalLayoutWidget)
        self.rb_ms_tracking.setObjectName(u"rb_ms_tracking")

        self.horizontalLayout_2.addWidget(self.rb_ms_tracking)

        self.rb_ms_return = QRadioButton(self.horizontalLayoutWidget)
        self.rb_ms_return.setObjectName(u"rb_ms_return")

        self.horizontalLayout_2.addWidget(self.rb_ms_return)

        self.rb_ms_stop = QRadioButton(self.horizontalLayoutWidget)
        self.rb_ms_stop.setObjectName(u"rb_ms_stop")

        self.horizontalLayout_2.addWidget(self.rb_ms_stop)

        self.label_connection_status = QLabel(self.frameRobotControlStatus)
        self.label_connection_status.setObjectName(u"label_connection_status")
        self.label_connection_status.setGeometry(QRect(460, 50, 101, 61))
        self.label_connection_status.setMaximumSize(QSize(16777215, 200))
        self.label_connection_status.setStyleSheet(u"background-color:yellow;")
        self.label_connection_status.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnAbnormalStop = QPushButton(self.frameRobotControlStatus)
        self.btnAbnormalStop.setObjectName(u"btnAbnormalStop")
        self.btnAbnormalStop.setGeometry(QRect(460, 150, 101, 101))
        self.btnAbnormalStop.setStyleSheet(u"background-color: red;\n"
"color: white;\n"
"font-size: 14px;\n"
"font-weight: bold;")
        self.frameRobotDeviceStatus = QFrame(mainForm)
        self.frameRobotDeviceStatus.setObjectName(u"frameRobotDeviceStatus")
        self.frameRobotDeviceStatus.setGeometry(QRect(0, 360, 581, 191))
        self.frameRobotDeviceStatus.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameRobotDeviceStatus.setFrameShadow(QFrame.Shadow.Raised)
        self.label_7 = QLabel(self.frameRobotDeviceStatus)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 0, 581, 41))
        self.label_7.setStyleSheet(u"background-color:rgb(207, 207, 207);\n"
"\n"
"")
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setMargin(4)
        self.gridLayoutWidget = QWidget(self.frameRobotDeviceStatus)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 50, 561, 131))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_17 = QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName(u"label_17")

        self.gridLayout.addWidget(self.label_17, 0, 2, 1, 1)

        self.label_19 = QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName(u"label_19")

        self.gridLayout.addWidget(self.label_19, 2, 2, 1, 1)

        self.label_21 = QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName(u"label_21")

        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)

        self.label_18 = QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName(u"label_18")

        self.gridLayout.addWidget(self.label_18, 1, 2, 1, 1)

        self.label_13 = QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName(u"label_13")

        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)

        self.robot_heading_degree = QLabel(self.gridLayoutWidget)
        self.robot_heading_degree.setObjectName(u"robot_heading_degree")
        self.robot_heading_degree.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.robot_heading_degree, 2, 1, 1, 1)

        self.label_robot_veloX = QLabel(self.gridLayoutWidget)
        self.label_robot_veloX.setObjectName(u"label_robot_veloX")
        self.label_robot_veloX.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_robot_veloX, 0, 1, 1, 1)

        self.label_robot_veloY = QLabel(self.gridLayoutWidget)
        self.label_robot_veloY.setObjectName(u"label_robot_veloY")
        self.label_robot_veloY.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_robot_veloY, 1, 1, 1, 1)

        self.label_20 = QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName(u"label_20")

        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)

        self.label_battery_level = QLabel(self.gridLayoutWidget)
        self.label_battery_level.setObjectName(u"label_battery_level")
        self.label_battery_level.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_battery_level, 0, 3, 1, 1)

        self.label_battery_temper = QLabel(self.gridLayoutWidget)
        self.label_battery_temper.setObjectName(u"label_battery_temper")
        self.label_battery_temper.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_battery_temper, 1, 3, 1, 1)

        self.label_battery_status = QLabel(self.gridLayoutWidget)
        self.label_battery_status.setObjectName(u"label_battery_status")
        self.label_battery_status.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout.addWidget(self.label_battery_status, 2, 3, 1, 1)

        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 1)
        self.labelBottomRightScreen = QLabel(mainForm)
        self.labelBottomRightScreen.setObjectName(u"labelBottomRightScreen")
        self.labelBottomRightScreen.setGeometry(QRect(10, 550, 561, 21))
        self.labelBottomRightScreen.setStyleSheet(u"border : none;")
        self.labelSubCamera = QLabel(mainForm)
        self.labelSubCamera.setObjectName(u"labelSubCamera")
        self.labelSubCamera.setGeometry(QRect(10, 820, 561, 21))
        self.labelSubCamera.setStyleSheet(u"border : none")
        self.systemExternalControl = QWidget(mainForm)
        self.systemExternalControl.setObjectName(u"systemExternalControl")
        self.systemExternalControl.setGeometry(QRect(590, 670, 341, 411))
        self.systemExternalControl.setStyleSheet(u"border : 1px solid black;\n"
"margin : 4px;\n"
"")
        
        self.groupBox_3 = QGroupBox(self.systemExternalControl)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 10, 311, 391))
        self.btn_view_eo = QPushButton(self.groupBox_3)
        self.btn_view_eo.setObjectName(u"btn_view_eo")
        self.btn_view_eo.setGeometry(QRect(20, 30, 91, 41))
        self.btn_view_ir = QPushButton(self.groupBox_3)
        self.btn_view_ir.setObjectName(u"btn_view_ir")
        self.btn_view_ir.setGeometry(QRect(110, 30, 91, 41))
        self.btn_view_stop = QPushButton(self.groupBox_3)
        self.btn_view_stop.setObjectName(u"btn_view_stop")
        self.btn_view_stop.setGeometry(QRect(200, 30, 91, 41))
        self.lbl_video_source = QLabel(self.groupBox_3)
        self.lbl_video_source.setObjectName(u"lbl_video_source")
        self.lbl_video_source.setGeometry(QRect(30, 70, 121, 31))
        self.lbl_video_source.setStyleSheet(u"color: gray; font-weight: bold;")
        self.lbl_conn_status = QLabel(self.groupBox_3)
        self.lbl_conn_status.setObjectName(u"lbl_conn_status")
        self.lbl_conn_status.setGeometry(QRect(160, 70, 111, 31))
        self.lbl_conn_status.setStyleSheet(u"color: red; font-weight: bold;")
        self.lbl_motor_status = QLabel(self.groupBox_3)
        self.lbl_motor_status.setObjectName(u"lbl_motor_status")
        self.lbl_motor_status.setGeometry(QRect(30, 100, 121, 31))
        self.lbl_power_status = QLabel(self.groupBox_3)
        self.lbl_power_status.setObjectName(u"lbl_power_status")
        self.lbl_power_status.setGeometry(QRect(160, 100, 111, 31))
        self.track_group = QGroupBox(self.groupBox_3)
        self.track_group.setObjectName(u"track_group")
        self.track_group.setGeometry(QRect(20, 140, 261, 121))
        self.lbl_track_status = QLabel(self.track_group)
        self.lbl_track_status.setObjectName(u"lbl_track_status")
        self.lbl_track_status.setGeometry(QRect(30, 30, 121, 31))
        self.btn_track_mode = QPushButton(self.track_group)
        self.btn_track_mode.setObjectName(u"btn_track_mode")
        self.btn_track_mode.setGeometry(QRect(20, 70, 111, 41))
        self.btn_track_stop = QPushButton(self.track_group)
        self.btn_track_stop.setObjectName(u"btn_track_stop")
        self.btn_track_stop.setGeometry(QRect(140, 70, 111, 41))
        self.camera_motor_speed_group = QGroupBox(self.groupBox_3)
        self.camera_motor_speed_group.setObjectName(u"camera_motor_speed_group")
        self.camera_motor_speed_group.setGeometry(QRect(20, 270, 261, 101))
        self.le_pan_speed = QLineEdit(self.camera_motor_speed_group)
        self.le_pan_speed.setObjectName(u"le_pan_speed")
        self.le_pan_speed.setGeometry(QRect(120, 20, 113, 31))
        self.le_pan_speed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.le_tilt_speed = QLineEdit(self.camera_motor_speed_group)
        self.le_tilt_speed.setObjectName(u"le_tilt_speed")
        self.le_tilt_speed.setGeometry(QRect(120, 60, 113, 31))
        self.le_tilt_speed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_track_status_2 = QLabel(self.camera_motor_speed_group)
        self.lbl_track_status_2.setObjectName(u"lbl_track_status_2")
        self.lbl_track_status_2.setGeometry(QRect(20, 20, 101, 31))
        self.lbl_track_status_3 = QLabel(self.camera_motor_speed_group)
        self.lbl_track_status_3.setObjectName(u"lbl_track_status_3")
        self.lbl_track_status_3.setGeometry(QRect(20, 60, 101, 31))
        
        self.retranslateUi(mainForm)

        QMetaObject.connectSlotsByName(mainForm)
    # setupUi

    def retranslateUi(self, mainForm):
        mainForm.setWindowTitle(QCoreApplication.translate("mainForm", u"Control System", None))
        self.btnGoHome.setText("")
        self.label_home.setText("")
        self.label_8.setText(QCoreApplication.translate("mainForm", u"\ud604\uc7ac\uc2dc\uac04", None))
        self.label_9.setText(QCoreApplication.translate("mainForm", u"\uc6b4\uc6a9\uc2dc\uac04", None))
        self.currentTime.setText(QCoreApplication.translate("mainForm", u"YYYY-MM-DD-HH-mm", None))
        self.operationTime.setText(QCoreApplication.translate("mainForm", u"HH-mm", None))
        self.label_10.setText("")
        self.txUnitNuberInfo.setText(QCoreApplication.translate("mainForm", u"N \ud638\uae30", None))
        self.label_11.setText("")
        self.btnGotoSetup.setText("")
        self.btnWaringJoin.setText(QCoreApplication.translate("mainForm", u"\uc778\uac00\uc790 \ub4f1\ub85d", None))
        self.btnWaringSend.setText(QCoreApplication.translate("mainForm", u"\uacbd\uace0 \uba54\uc2dc\uc9c0 \ubc1c\uc1a1", None))
        self.mainCamScreen_bmpLabel.setText("")
        self.btnZoomIn.setText("")
        self.label_3.setText("")
        self.pushButton_cmd_Send.setText(QCoreApplication.translate("mainForm", u"Enter", None))
        self.lbl_systemlog.setText(QCoreApplication.translate("mainForm", u"\uc2dc\uc2a4\ud15c \ub85c\uadf8", None))
        self.label.setText(QCoreApplication.translate("mainForm", u"<html><head/><body><p><span style=\" font-size:12pt;\">\ub85c\ubd07\uc0c1\ud0dc\uc804\uc2dc</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("mainForm", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">\uc6b4\uc6a9\ubaa8\ub4dc\uc120\ud0dd</span></p></body></html>", None))
        self.groupBox.setTitle("")
        self.rb_opmode_auto.setText(QCoreApplication.translate("mainForm", u"AUTO(\uc790\uc728)", None))
        self.rb_opmode_operator.setText(QCoreApplication.translate("mainForm", u"Operation(\uc6d0\uaca9)", None))
        self.rb_opmode_manual.setText(QCoreApplication.translate("mainForm", u"MANUAL(\ud734\ub300\uc6a9)", None))
        self.label_6.setText(QCoreApplication.translate("mainForm", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">\uc784\ubb34\uc218\ud589\uc0c1\ud0dc(\uc9c0\ub839 \uc784\ubb34)</span></p></body></html>", None))
        self.groupBox_2.setTitle("")
        self.rb_ms_move.setText(QCoreApplication.translate("mainForm", u"\uc774\ub3d9", None))
        self.rb_ms_patrol.setText(QCoreApplication.translate("mainForm", u"\uac10\uc2dc", None))
        self.rb_ms_tracking.setText(QCoreApplication.translate("mainForm", u"\ucd94\uc801", None))
        self.rb_ms_return.setText(QCoreApplication.translate("mainForm", u"\ubcf5\uadc0", None))
        self.rb_ms_stop.setText(QCoreApplication.translate("mainForm", u"\uc885\ub8cc", None))
        self.label_connection_status.setText(QCoreApplication.translate("mainForm", u"Wait", None))
        self.btnAbnormalStop.setText(QCoreApplication.translate("mainForm", u"\ube44\uc0c1\uc815\uc9c0", None))
        self.label_7.setText(QCoreApplication.translate("mainForm", u"<html><head/><body><p><span style=\" font-size:12pt;\">\ub85c\ubd07\uae30\uad6c\ud559 \ubc0f \ubca0\ud130\ub9ac \uc0c1\ud0dc \ud45c\uc2dc</span></p></body></html>", None))
        self.label_17.setText(QCoreApplication.translate("mainForm", u"\ubc30\ud130\ub9ac\uc794\ub7c9(%)", None))
        self.label_19.setText(QCoreApplication.translate("mainForm", u"\ubc30\ud130\ub9ac\uc0c1\ud0dc", None))
        self.label_21.setText(QCoreApplication.translate("mainForm", u"<html><head/><body><p>\ub85c\ubd07 \ud5e4\ub529 \uac01\ub3c4[Degree]</p></body></html>", None))
        self.label_18.setText(QCoreApplication.translate("mainForm", u"\ubca0\ud130\ub9ac\uc628\ub3c4(C)", None))
        self.label_13.setText(QCoreApplication.translate("mainForm", u"\ub85c\ubd07X\ucd95 \uc120\uc18d\ub3c4[m/s] :", None))
        self.robot_heading_degree.setText(QCoreApplication.translate("mainForm", u"0", None))
        self.label_robot_veloX.setText(QCoreApplication.translate("mainForm", u"0", None))
        self.label_robot_veloY.setText(QCoreApplication.translate("mainForm", u"0", None))
        self.label_20.setText(QCoreApplication.translate("mainForm", u"\ub85c\ubd07Y\ucd95 \uc120\uc18d\ub3c4[m/s] :", None))
        self.label_battery_level.setText(QCoreApplication.translate("mainForm", u"0", None))
        self.label_battery_temper.setText(QCoreApplication.translate("mainForm", u"0", None))
        self.label_battery_status.setText(QCoreApplication.translate("mainForm", u"0", None))
        self.labelBottomRightScreen.setText(QCoreApplication.translate("mainForm", u"\ub85c\ubd07 \uc704\uce58 \uc815\ubcf4", None))
        self.labelSubCamera.setText(QCoreApplication.translate("mainForm", u"\ub85c\ubd07 \uc8fc\ud589 \uce74\uba54\ub77c \uc601\uc0c1", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("mainForm", u"\uac10\uc2dc\uc7a5\ube44 \uc81c\uc5b4", None))
        self.btn_view_eo.setText(QCoreApplication.translate("mainForm", u"EO \uc601\uc0c1 \ubcf4\uae30", None))
        self.btn_view_ir.setText(QCoreApplication.translate("mainForm", u"IR \uc601\uc0c1 \ubcf4\uae30", None))
        self.btn_view_stop.setText(QCoreApplication.translate("mainForm", u"\uc601\uc0c1 \uc911\uc9c0", None))
        self.lbl_video_source.setText(QCoreApplication.translate("mainForm", u"\uc18c\uc2a4 : N/A", None))
        self.lbl_conn_status.setText(QCoreApplication.translate("mainForm", u"\u25cf \ubbf8\uc5f0\uacb0", None))
        self.lbl_motor_status.setText(QCoreApplication.translate("mainForm", u"Pan: --, Tilt: --", None))
        self.lbl_power_status.setText(QCoreApplication.translate("mainForm", u"EO: ?, IR: ?", None))
        self.track_group.setTitle(QCoreApplication.translate("mainForm", u"\ucd94\uc801 \uc81c\uc5b4", None))
        self.lbl_track_status.setText(QCoreApplication.translate("mainForm", u"\ubbf8\ucd94\uc801", None))
        self.btn_track_mode.setText(QCoreApplication.translate("mainForm", u"\ucd94\uc801 \uc124\uc815", None))
        self.btn_track_stop.setText(QCoreApplication.translate("mainForm", u"\ucd94\uc801 \uc911\uc9c0", None))
        self.camera_motor_speed_group.setTitle(QCoreApplication.translate("mainForm", u"\ubaa8\ud130 \uc81c\uc5b4 \uc18d\ub3c4", None))
        self.le_pan_speed.setText(QCoreApplication.translate("mainForm", u"15.0", None))
        self.le_tilt_speed.setText(QCoreApplication.translate("mainForm", u"10.0", None))
        self.lbl_track_status_2.setText(QCoreApplication.translate("mainForm", u"\ud32c \ubaa8\ud130 \uc18d\ub3c4 :", None))
        self.lbl_track_status_3.setText(QCoreApplication.translate("mainForm", u"\ud2f8\ud2b8 \ubaa8\ud130 \uc18d\ub3c4 :", None))
        self.label_keydown_normal.setText("")
        self.label_keydown_push.setText("")
        self.btnKeyDown.setText("")
        self.label_keyleft_normal.setText("")
        self.label_keyleft_push.setText("")
        self.btnKeyLeft.setText("")
        self.label_keyup_normal.setText("")
        self.label_keyup_push.setText("")
        self.btnKeyUp.setText("")
        self.label_keyright_normal.setText("")
        self.label_keyright_push.setText("")
        self.btnKeyRight.setText("")
        self.label_4.setText("")
        self.label_12.setText(QCoreApplication.translate("mainForm", u"<html><head/><body><p><span style=\" font-size:12pt;\">\ub85c\ubd07 \uc218\ub3d9 \uc870\uc774\uc2a4\ud2f1(UI)</span></p></body></html>", None))
    # retranslateUi

