# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'setupForm.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QSpacerItem, QWidget)

class Ui_SetupForm(object):
    def setupUi(self, SetupForm):
        if not SetupForm.objectName():
            SetupForm.setObjectName(u"SetupForm")
        SetupForm.resize(1095, 892)
        self.label = QLabel(SetupForm)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 60, 111, 16))
        self.ControlFrame = QFrame(SetupForm)
        self.ControlFrame.setObjectName(u"ControlFrame")
        self.ControlFrame.setGeometry(QRect(20, 80, 681, 191))
        self.ControlFrame.setStyleSheet(u"background-color : white;")
        self.ControlFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.ControlFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.widgetScreenSetting = QWidget(self.ControlFrame)
        self.widgetScreenSetting.setObjectName(u"widgetScreenSetting")
        self.widgetScreenSetting.setGeometry(QRect(10, 90, 601, 61))
        self.widgetScreenSetting.setStyleSheet(u"border : 1px solid black;\n"
"")
        self.horizontalLayout_2 = QHBoxLayout(self.widgetScreenSetting)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.screenconfig_label = QLabel(self.widgetScreenSetting)
        self.screenconfig_label.setObjectName(u"screenconfig_label")

        self.horizontalLayout_2.addWidget(self.screenconfig_label)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)

        self.btnFullScreenOn = QPushButton(self.widgetScreenSetting)
        self.btnFullScreenOn.setObjectName(u"btnFullScreenOn")
        self.btnFullScreenOn.setMinimumSize(QSize(96, 32))

        self.horizontalLayout_2.addWidget(self.btnFullScreenOn)

        self.btnFullScreenOff = QPushButton(self.widgetScreenSetting)
        self.btnFullScreenOff.setObjectName(u"btnFullScreenOff")
        self.btnFullScreenOff.setMinimumSize(QSize(96, 32))

        self.horizontalLayout_2.addWidget(self.btnFullScreenOff)

        self.widgetSoundSetting = QWidget(self.ControlFrame)
        self.widgetSoundSetting.setObjectName(u"widgetSoundSetting")
        self.widgetSoundSetting.setGeometry(QRect(10, 20, 601, 61))
        self.widgetSoundSetting.setStyleSheet(u"border : 1px solid black;\n"
"")
        self.horizontalLayout = QHBoxLayout(self.widgetSoundSetting)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.soundconfiglabel = QLabel(self.widgetSoundSetting)
        self.soundconfiglabel.setObjectName(u"soundconfiglabel")

        self.horizontalLayout.addWidget(self.soundconfiglabel)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.btnSoundOn = QPushButton(self.widgetSoundSetting)
        self.btnSoundOn.setObjectName(u"btnSoundOn")
        self.btnSoundOn.setMinimumSize(QSize(96, 32))

        self.horizontalLayout.addWidget(self.btnSoundOn)

        self.btnSoundOff = QPushButton(self.widgetSoundSetting)
        self.btnSoundOff.setObjectName(u"btnSoundOff")
        self.btnSoundOff.setMinimumSize(QSize(96, 32))

        self.horizontalLayout.addWidget(self.btnSoundOff)

        self.btnBack = QPushButton(SetupForm)
        self.btnBack.setObjectName(u"btnBack")
        self.btnBack.setGeometry(QRect(30, 20, 61, 32))
        self.pushButton_saveSetup = QPushButton(SetupForm)
        self.pushButton_saveSetup.setObjectName(u"pushButton_saveSetup")
        self.pushButton_saveSetup.setGeometry(QRect(930, 50, 75, 24))
        self.DectectionServerConfig = QGroupBox(SetupForm)
        self.DectectionServerConfig.setObjectName(u"DectectionServerConfig")
        self.DectectionServerConfig.setGeometry(QRect(710, 300, 351, 111))
        self.label_7 = QLabel(self.DectectionServerConfig)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 20, 31, 16))
        self.label_11 = QLabel(self.DectectionServerConfig)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(240, 20, 31, 16))
        self.cbEnableImgDetection = QCheckBox(self.DectectionServerConfig)
        self.cbEnableImgDetection.setObjectName(u"cbEnableImgDetection")
        self.cbEnableImgDetection.setGeometry(QRect(20, 80, 79, 20))
        self.lineEdit_detecter_ip = QLineEdit(self.DectectionServerConfig)
        self.lineEdit_detecter_ip.setObjectName(u"lineEdit_detecter_ip")
        self.lineEdit_detecter_ip.setGeometry(QRect(10, 50, 191, 22))
        self.lineEdit_detecter_port = QLineEdit(self.DectectionServerConfig)
        self.lineEdit_detecter_port.setObjectName(u"lineEdit_detecter_port")
        self.lineEdit_detecter_port.setGeometry(QRect(222, 50, 91, 22))
        self.Unit_1 = QGroupBox(SetupForm)
        self.Unit_1.setObjectName(u"Unit_1")
        self.Unit_1.setGeometry(QRect(20, 300, 461, 150))
        self.label_3 = QLabel(self.Unit_1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 20, 31, 16))
        self.label_5 = QLabel(self.Unit_1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 70, 71, 16))
        self.label_4 = QLabel(self.Unit_1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(240, 20, 31, 16))
        self.cbUnit_1_Enable = QCheckBox(self.Unit_1)
        self.cbUnit_1_Enable.setObjectName(u"cbUnit_1_Enable")
        self.cbUnit_1_Enable.setGeometry(QRect(370, 20, 79, 20))
        self.textEditCar1ip = QLineEdit(self.Unit_1)
        self.textEditCar1ip.setObjectName(u"textEditCar1ip")
        self.textEditCar1ip.setGeometry(QRect(10, 41, 221, 21))
        self.textEditCar1port = QLineEdit(self.Unit_1)
        self.textEditCar1port.setObjectName(u"textEditCar1port")
        self.textEditCar1port.setGeometry(QRect(240, 40, 113, 22))
        self.textEditCar1Camurl_rgb = QLineEdit(self.Unit_1)
        self.textEditCar1Camurl_rgb.setObjectName(u"textEditCar1Camurl_rgb")
        self.textEditCar1Camurl_rgb.setGeometry(QRect(50, 90, 391, 22))
        self.textEditCar1Camurl_IR = QLineEdit(self.Unit_1)
        self.textEditCar1Camurl_IR.setObjectName(u"textEditCar1Camurl_IR")
        self.textEditCar1Camurl_IR.setGeometry(QRect(50, 120, 391, 22))
        self.label_2 = QLabel(self.Unit_1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 31, 16))
        self.label_14 = QLabel(self.Unit_1)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 120, 31, 16))
        self.Unit_2 = QGroupBox(SetupForm)
        self.Unit_2.setObjectName(u"Unit_2")
        self.Unit_2.setGeometry(QRect(20, 460, 461, 150))
        self.label_12 = QLabel(self.Unit_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 20, 31, 16))
        self.label_13 = QLabel(self.Unit_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 70, 71, 16))
        self.label_16 = QLabel(self.Unit_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(240, 20, 31, 16))
        self.cbUnit_2_Enable = QCheckBox(self.Unit_2)
        self.cbUnit_2_Enable.setObjectName(u"cbUnit_2_Enable")
        self.cbUnit_2_Enable.setGeometry(QRect(370, 20, 79, 20))
        self.textEditCar2ip = QLineEdit(self.Unit_2)
        self.textEditCar2ip.setObjectName(u"textEditCar2ip")
        self.textEditCar2ip.setGeometry(QRect(10, 41, 221, 21))
        self.textEditCar2port = QLineEdit(self.Unit_2)
        self.textEditCar2port.setObjectName(u"textEditCar2port")
        self.textEditCar2port.setGeometry(QRect(240, 40, 113, 22))
        self.textEditCar2Camurl_rgb = QLineEdit(self.Unit_2)
        self.textEditCar2Camurl_rgb.setObjectName(u"textEditCar2Camurl_rgb")
        self.textEditCar2Camurl_rgb.setGeometry(QRect(50, 90, 391, 22))
        self.textEditCar2Camurl_IR = QLineEdit(self.Unit_2)
        self.textEditCar2Camurl_IR.setObjectName(u"textEditCar2Camurl_IR")
        self.textEditCar2Camurl_IR.setGeometry(QRect(50, 120, 391, 22))
        self.label_17 = QLabel(self.Unit_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 100, 31, 16))
        self.label_18 = QLabel(self.Unit_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 120, 31, 16))
        self.Unit_3 = QGroupBox(SetupForm)
        self.Unit_3.setObjectName(u"Unit_3")
        self.Unit_3.setGeometry(QRect(20, 630, 461, 150))
        self.label_19 = QLabel(self.Unit_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 20, 31, 16))
        self.label_20 = QLabel(self.Unit_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 70, 71, 16))
        self.label_21 = QLabel(self.Unit_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(240, 20, 31, 16))
        self.cbUnit_3_Enable = QCheckBox(self.Unit_3)
        self.cbUnit_3_Enable.setObjectName(u"cbUnit_3_Enable")
        self.cbUnit_3_Enable.setGeometry(QRect(370, 20, 79, 20))
        self.textEditCar3ip = QLineEdit(self.Unit_3)
        self.textEditCar3ip.setObjectName(u"textEditCar3ip")
        self.textEditCar3ip.setGeometry(QRect(10, 41, 221, 21))
        self.textEditCar3port = QLineEdit(self.Unit_3)
        self.textEditCar3port.setObjectName(u"textEditCar3port")
        self.textEditCar3port.setGeometry(QRect(240, 40, 113, 22))
        self.textEditCar3Camurl_rgb = QLineEdit(self.Unit_3)
        self.textEditCar3Camurl_rgb.setObjectName(u"textEditCar3Camurl_rgb")
        self.textEditCar3Camurl_rgb.setGeometry(QRect(50, 90, 391, 22))
        self.textEditCar3Camurl_IR = QLineEdit(self.Unit_3)
        self.textEditCar3Camurl_IR.setObjectName(u"textEditCar3Camurl_IR")
        self.textEditCar3Camurl_IR.setGeometry(QRect(50, 120, 391, 22))
        self.label_22 = QLabel(self.Unit_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 100, 31, 16))
        self.label_23 = QLabel(self.Unit_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 120, 31, 16))
        self.frameUnitSlect = QFrame(SetupForm)
        self.frameUnitSlect.setObjectName(u"frameUnitSlect")
        self.frameUnitSlect.setGeometry(QRect(710, 520, 231, 131))
        self.frameUnitSlect.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameUnitSlect.setFrameShadow(QFrame.Shadow.Raised)
        self.label_6 = QLabel(self.frameUnitSlect)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 40, 121, 16))
        self.lineEditSelectUnitIndex = QLineEdit(self.frameUnitSlect)
        self.lineEditSelectUnitIndex.setObjectName(u"lineEditSelectUnitIndex")
        self.lineEditSelectUnitIndex.setGeometry(QRect(140, 30, 71, 31))
        self.lineEditSelectUnitIndex.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEditSelectUnitIndex_Sub = QLineEdit(self.frameUnitSlect)
        self.lineEditSelectUnitIndex_Sub.setObjectName(u"lineEditSelectUnitIndex_Sub")
        self.lineEditSelectUnitIndex_Sub.setGeometry(QRect(140, 80, 71, 31))
        self.lineEditSelectUnitIndex_Sub.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_8 = QLabel(self.frameUnitSlect)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 90, 121, 16))
        self.checkBox_fullScreen = QCheckBox(SetupForm)
        self.checkBox_fullScreen.setObjectName(u"checkBox_fullScreen")
        self.checkBox_fullScreen.setGeometry(QRect(720, 740, 79, 20))

        self.retranslateUi(SetupForm)

        QMetaObject.connectSlotsByName(SetupForm)
    # setupUi

    def retranslateUi(self, SetupForm):
        SetupForm.setWindowTitle(QCoreApplication.translate("SetupForm", u"\uc124\uc815", None))
        self.label.setText(QCoreApplication.translate("SetupForm", u"\uc81c\uc5b4\ud504\ub85c\uadf8\ub7a8\uc124\uc815", None))
        self.screenconfig_label.setText(QCoreApplication.translate("SetupForm", u"\ud654\uba74\uc124\uc815", None))
        self.btnFullScreenOn.setText(QCoreApplication.translate("SetupForm", u"\ucf2c", None))
        self.btnFullScreenOff.setText(QCoreApplication.translate("SetupForm", u"\ub054", None))
        self.soundconfiglabel.setText(QCoreApplication.translate("SetupForm", u"\uc0ac\uc6b4\ub4dc\uc124\uc815", None))
        self.btnSoundOn.setText(QCoreApplication.translate("SetupForm", u"\ucf2c", None))
        self.btnSoundOff.setText(QCoreApplication.translate("SetupForm", u"\ub054", None))
        self.btnBack.setText(QCoreApplication.translate("SetupForm", u"<<", None))
        self.pushButton_saveSetup.setText(QCoreApplication.translate("SetupForm", u"Save", None))
        self.DectectionServerConfig.setTitle(QCoreApplication.translate("SetupForm", u"Image detection Server", None))
        self.label_7.setText(QCoreApplication.translate("SetupForm", u"ip", None))
        self.label_11.setText(QCoreApplication.translate("SetupForm", u"port", None))
        self.cbEnableImgDetection.setText(QCoreApplication.translate("SetupForm", u"Enable", None))
        self.Unit_1.setTitle(QCoreApplication.translate("SetupForm", u"1 \ud638\uae30", None))
        self.label_3.setText(QCoreApplication.translate("SetupForm", u"ip", None))
        self.label_5.setText(QCoreApplication.translate("SetupForm", u"cam url", None))
        self.label_4.setText(QCoreApplication.translate("SetupForm", u"port", None))
        self.cbUnit_1_Enable.setText(QCoreApplication.translate("SetupForm", u"Enable", None))
        self.label_2.setText(QCoreApplication.translate("SetupForm", u"RGB", None))
        self.label_14.setText(QCoreApplication.translate("SetupForm", u"IR", None))
        self.Unit_2.setTitle(QCoreApplication.translate("SetupForm", u"2 \ud638\uae30", None))
        self.label_12.setText(QCoreApplication.translate("SetupForm", u"ip", None))
        self.label_13.setText(QCoreApplication.translate("SetupForm", u"cam url", None))
        self.label_16.setText(QCoreApplication.translate("SetupForm", u"port", None))
        self.cbUnit_2_Enable.setText(QCoreApplication.translate("SetupForm", u"Enable", None))
        self.label_17.setText(QCoreApplication.translate("SetupForm", u"RGB", None))
        self.label_18.setText(QCoreApplication.translate("SetupForm", u"IR", None))
        self.Unit_3.setTitle(QCoreApplication.translate("SetupForm", u"3 \ud638\uae30", None))
        self.label_19.setText(QCoreApplication.translate("SetupForm", u"ip", None))
        self.label_20.setText(QCoreApplication.translate("SetupForm", u"cam url", None))
        self.label_21.setText(QCoreApplication.translate("SetupForm", u"port", None))
        self.cbUnit_3_Enable.setText(QCoreApplication.translate("SetupForm", u"Enable", None))
        self.label_22.setText(QCoreApplication.translate("SetupForm", u"RGB", None))
        self.label_23.setText(QCoreApplication.translate("SetupForm", u"IR", None))
        self.label_6.setText(QCoreApplication.translate("SetupForm", u"Main Unit Index :", None))
        self.lineEditSelectUnitIndex.setText(QCoreApplication.translate("SetupForm", u"1", None))
        self.lineEditSelectUnitIndex_Sub.setText(QCoreApplication.translate("SetupForm", u"2", None))
        self.label_8.setText(QCoreApplication.translate("SetupForm", u"Sub Unit Index :", None))
        self.checkBox_fullScreen.setText(QCoreApplication.translate("SetupForm", u"FullScreen", None))
    # retranslateUi

